// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_join_requests.sql

package db_queries

import (
	"context"
)

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO club_join_requests 
(club_id, user_id, status)
VALUES 
($1, $2, $3)
RETURNING id, club_id, user_id, status, created_at, updated_at, is_deleted
`

type CreateJoinRequestParams struct {
	ClubID int64
	UserID int64
	Status string
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (ClubJoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.ClubID, arg.UserID, arg.Status)
	var i ClubJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getJoinRequests = `-- name: GetJoinRequests :many
SELECT cjr.id, cjr.club_id, cjr.user_id, cjr.status, cjr.created_at, cjr.updated_at, cjr.is_deleted
FROM club_join_requests cjr
INNER JOIN clubs c ON cjr.club_id = c.id
WHERE 
    ($1::bigint IS NULL OR cjr.id = $1::bigint)
    AND ($2::bigint IS NULL OR cjr.club_id = $2::bigint)
    AND ($3::bigint IS NULL OR cjr.user_id = $3::bigint)
    AND cjr.is_deleted = false
    AND (
        cjr.user_id = $4
        OR c.teacher_id = $4
    )
ORDER BY cjr.created_at DESC
LIMIT $6::bigint
OFFSET $5::bigint
`

type GetJoinRequestsParams struct {
	ID            *int64
	ClubID        *int64
	UserID        *int64
	CurrentUserID int64
	Offset        *int64
	Limit         *int64
}

func (q *Queries) GetJoinRequests(ctx context.Context, arg GetJoinRequestsParams) ([]ClubJoinRequest, error) {
	rows, err := q.db.Query(ctx, getJoinRequests,
		arg.ID,
		arg.ClubID,
		arg.UserID,
		arg.CurrentUserID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubJoinRequest{}
	for rows.Next() {
		var i ClubJoinRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClubJoinRequestStatus = `-- name: UpdateClubJoinRequestStatus :one
UPDATE club_join_requests
SET
    status = $1,
    updated_at = now()
WHERE id = $2 and is_deleted = FALSE
RETURNING club_join_requests.id, club_join_requests.club_id, club_join_requests.user_id, club_join_requests.status, club_join_requests.created_at, club_join_requests.updated_at, club_join_requests.is_deleted
`

type UpdateClubJoinRequestStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateClubJoinRequestStatus(ctx context.Context, arg UpdateClubJoinRequestStatusParams) (ClubJoinRequest, error) {
	row := q.db.QueryRow(ctx, updateClubJoinRequestStatus, arg.Status, arg.ID)
	var i ClubJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
