// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"context"
)

type Querier interface {
	CheckClubExists(ctx context.Context, id int64) (bool, error)
	CheckClubOwnership(ctx context.Context, arg CheckClubOwnershipParams) (bool, error)
	CheckEducationLevelExistsByName(ctx context.Context, name string) (bool, error)
	CheckIfEmailIsRegistered(ctx context.Context, email string) (bool, error)
	CheckIfPhoneIsRegistered(ctx context.Context, phoneNumber string) (bool, error)
	CheckIfSocialNetworkIsRegistered(ctx context.Context, socialNetworkLink string) (bool, error)
	CheckSportTypeExists(ctx context.Context, id int64) (bool, error)
	CheckWorkoutExists(ctx context.Context, id int64) (bool, error)
	CheckWorkoutOwnership(ctx context.Context, arg CheckWorkoutOwnershipParams) (bool, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (ClubJoinRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteUser(ctx context.Context, email string) error
	GetAllClubs(ctx context.Context) ([]GetAllClubsRow, error)
	GetClubAttachments(ctx context.Context, id int64) ([]string, error)
	GetClubByID(ctx context.Context, id int64) (Club, error)
	GetClubById(ctx context.Context, id int64) (GetClubByIdRow, error)
	GetClubsByTeacher(ctx context.Context, teacherID int64) ([]Club, error)
	GetJoinRequests(ctx context.Context, arg GetJoinRequestsParams) ([]ClubJoinRequest, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	GetWorkoutsByClub(ctx context.Context, clubID int64) ([]GetWorkoutsByClubRow, error)
	ListActiveClubs(ctx context.Context) ([]Club, error)
	SoftDeleteClub(ctx context.Context, id int64) error
	SoftDeleteWorkout(ctx context.Context, id int64) error
	UpdateClubJoinRequestStatus(ctx context.Context, arg UpdateClubJoinRequestStatusParams) (ClubJoinRequest, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error)
	UploadAttachment(ctx context.Context, arg UploadAttachmentParams) error
}

var _ Querier = (*Queries)(nil)
