apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sport-platform
resources:
  - namespace.yaml
  - ../../base
images:
  - name: sport-platform-backend
    newTag: 1.0.0
  - name: sport-platform-frontend
    newTag: 1.0.0
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: frontend-service-patch.yaml
  - path: hpa-patch.yaml
