apiVersion: v1
kind: ConfigMap
metadata:
  name: sport-platform-config
data:
  HOST: postgres-0.postgres.sport-platform-infra-prod.svc.cluster.local
  DB_NAME: sport_platform
  DEMO_SEED: "false"
  CORS_ALLOWED_ORIGINS: https://sport.example.com,https://api.sport.example.com
  AUTH_URL: https://sport.example.com
  NEXTAUTH_URL: https://sport.example.com
  BACKEND_API_URL: http://backend-service:8080
  NEXT_PUBLIC_API_URL: https://api.sport.example.com
