apiVersion: v1
kind: Secret
metadata:
  name: sport-platform-secret
stringData:
  USERNAME: sport
  PASSWORD: change_me_with_external_secret
  ACCESS_SECRET: change_me_access_secret
  REFRESH_SECRET: change_me_refresh_secret
  AUTH_SECRET: change_me_auth_secret_32_chars_min
  MINIO_ACCESS_KEY: change_me_minio_access_key
  MINIO_SECRET_KEY: change_me_minio_secret_key
