// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"time"
)

type Achievement struct {
	ID        int64
	UserID    int64
	EventID   int64
	Place     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Attachment struct {
	ID        int64
	Filename  string
	TypeID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type AttachmentType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	IsDeleted bool
}

type Club struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
	IsDeleted              bool
}

type ClubAttachment struct {
	ClubID        int64
	AttachmentUrl string
}

type ClubJoinRequest struct {
	ID        int64
	ClubID    int64
	UserID    int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type EducationLevel struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Event struct {
	ID             int64
	Name           string
	Description    string
	StartDate      time.Time
	EndDate        time.Time
	LivestreamLink *string
	SportTypeID    int64
	CreatorID      int64
	TypeID         int64
	TotalPlaces    *int32
	Place          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
}

type EventJoinRequest struct {
	ID        int64
	EventID   int64
	UserID    int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type EventType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Group struct {
	ID             int64
	Institute      string
	EnrollmentYear int32
	Prefix         *string
	GroupTypeID    int64
	GroupNumber    *int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
}

type GroupType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Metric struct {
	ID          int64
	Name        string
	Description string
	Units       string
	ClubID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsDeleted   bool
}

type MetricsTarget struct {
	MetricID  int64
	UserID    int64
	Value     float64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Post struct {
	ID        int64
	Title     string
	Content   string
	CreatorID int64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type PostAttachment struct {
	PostID       int64
	AttachmentID int64
}

type PostTag struct {
	PostID int64
	TagID  int64
}

type Review struct {
	ID        int64
	Rating    int32
	Content   string
	CreatorID int64
	ClubID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type ReviewAttachment struct {
	ReviewID     int64
	AttachmentID int64
}

type SportType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type User struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	GroupID           *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsDeleted         bool
}

type Workout struct {
	ID        int64
	ClubID    int64
	StartDate time.Time
	EndDate   time.Time
	Cancelled bool
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type WorkoutAttendee struct {
	ID        int64
	WorkoutID int64
	RequestID int64
	Visited   bool
	Review    *string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type WorkoutMetric struct {
	WorkoutAttendeeID int64
	MetricID          int64
	Value             float64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsDeleted         bool
}
