// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db_queries

import (
	"context"
	"time"
)

const checkIfEmailIsRegistered = `-- name: CheckIfEmailIsRegistered :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1 AND is_deleted = FALSE
) AS email_exists
`

func (q *Queries) CheckIfEmailIsRegistered(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfEmailIsRegistered, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const checkIfPhoneIsRegistered = `-- name: CheckIfPhoneIsRegistered :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE phone_number = $1 AND is_deleted = FALSE
) AS phone_exists
`

func (q *Queries) CheckIfPhoneIsRegistered(ctx context.Context, phoneNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfPhoneIsRegistered, phoneNumber)
	var phone_exists bool
	err := row.Scan(&phone_exists)
	return phone_exists, err
}

const checkIfSocialNetworkIsRegistered = `-- name: CheckIfSocialNetworkIsRegistered :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE social_network_link = $1 AND is_deleted = FALSE
) AS network_exists
`

func (q *Queries) CheckIfSocialNetworkIsRegistered(ctx context.Context, socialNetworkLink string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfSocialNetworkIsRegistered, socialNetworkLink)
	var network_exists bool
	err := row.Scan(&network_exists)
	return network_exists, err
}

const createUser = `-- name: CreateUser :one
WITH user_info AS (
    INSERT INTO users
    (full_name, social_network_link, phone_number, email, birth_date, role, password, group_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, full_name, social_network_link, phone_number, email, birth_date, role, password, group_id, created_at, updated_at, is_deleted
)
SELECT 
    user_info.id, user_info.full_name, user_info.social_network_link, user_info.phone_number, user_info.email, user_info.birth_date, user_info.role, user_info.password, user_info.group_id, user_info.created_at, user_info.updated_at, user_info.is_deleted,
    CASE 
        WHEN groups.id IS NOT NULL THEN
            (groups.prefix || '-' || 
             extract(YEAR FROM age(now(), (groups.enrollment_year::text || '-09-01 00:00:00')::timestamptz)) + 1 || 
             lpad(groups.group_number::text, 2, '0') || 
             group_types.name || '-' || 
             substring(groups.enrollment_year::text FROM 3 FOR 2)
            )::text
        ELSE ''
    END as group_name
FROM user_info
LEFT JOIN groups ON groups.id = user_info.group_id AND groups.is_deleted = false
LEFT JOIN group_types ON groups.group_type_id = group_types.id AND group_types.is_deleted = false
`

type CreateUserParams struct {
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	GroupID           *int64
}

type CreateUserRow struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	GroupID           *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsDeleted         bool
	GroupName         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.SocialNetworkLink,
		arg.PhoneNumber,
		arg.Email,
		arg.BirthDate,
		arg.Role,
		arg.Password,
		arg.GroupID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.SocialNetworkLink,
		&i.PhoneNumber,
		&i.Email,
		&i.BirthDate,
		&i.Role,
		&i.Password,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.GroupName,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET
    is_deleted = true
WHERE email = $1 and is_deleted = false
`

func (q *Queries) DeleteUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUser, email)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    users.id,
    users.full_name,
    users.social_network_link,
    users.phone_number,
    users.email,
    users.birth_date,
    users.role,
    users.password,
    users.created_at,
    users.updated_at,
    COALESCE((
        SELECT
            groups.prefix || '-' ||
            (extract(YEAR FROM age(now(), (groups.enrollment_year::text || '-09-01 00:00:00')::timestamptz)) + 1)::text ||
            lpad(groups.group_number::text, 2, '0') ||
            group_types.name || '-' ||
            substring(groups.enrollment_year::text FROM 3 FOR 2)
        FROM groups
        LEFT JOIN group_types ON groups.group_type_id = group_types.id
        WHERE groups.id = users.group_id
    ), '')::text as group_name
FROM users
LEFT JOIN groups on users.group_id = groups.id AND groups.is_deleted = false
LEFT JOIN group_types on groups.group_type_id = group_types.id and group_types.is_deleted = false
WHERE users.email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	GroupName         string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.SocialNetworkLink,
		&i.PhoneNumber,
		&i.Email,
		&i.BirthDate,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupName,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    users.id,
    users.full_name,
    users.social_network_link,
    users.phone_number,
    users.email,
    users.birth_date,
    users.role,
    users.password,
    users.created_at,
    users.updated_at,
   COALESCE((
        SELECT
            groups.prefix || '-' ||
            (extract(YEAR FROM age(now(), (groups.enrollment_year::text || '-09-01 00:00:00')::timestamptz)) + 1)::text ||
            lpad(groups.group_number::text, 2, '0') ||
            group_types.name || '-' ||
            substring(groups.enrollment_year::text FROM 3 FOR 2)
        FROM groups
        LEFT JOIN group_types ON groups.group_type_id = group_types.id
        WHERE groups.id = users.group_id
    ), '')::text as group_name
FROM users
         LEFT JOIN groups on users.group_id = groups.id AND groups.is_deleted = false
         LEFT JOIN group_types on groups.group_type_id = group_types.id and group_types.is_deleted = false
WHERE users.id = $1
    LIMIT 1
`

type GetUserByIdRow struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	GroupName         string
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.SocialNetworkLink,
		&i.PhoneNumber,
		&i.Email,
		&i.BirthDate,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupName,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = COALESCE($1, full_name),
    social_network_link = COALESCE($2, social_network_link),
    phone_number = COALESCE($3, phone_number),
    email = COALESCE($4, email),
    password = COALESCE($5, password),
    updated_at = NOW()
WHERE users.id = $6
RETURNING
    users.id, users.full_name, users.social_network_link, users.phone_number, users.email, users.birth_date, users.role, users.password, users.group_id, users.created_at, users.updated_at, users.is_deleted,
    COALESCE((
        SELECT
            groups.prefix || '-' ||
            (extract(YEAR FROM age(now(), (groups.enrollment_year::text || '-09-01 00:00:00')::timestamptz)) + 1)::text ||
            lpad(groups.group_number::text, 2, '0') ||
            group_types.name || '-' ||
            substring(groups.enrollment_year::text FROM 3 FOR 2)
        FROM groups
        LEFT JOIN group_types ON groups.group_type_id = group_types.id
        WHERE groups.id = users.group_id
 ), '')::text as group_name
`

type UpdateUserParams struct {
	FullName          *string
	SocialNetworkLink *string
	PhoneNumber       *string
	Email             *string
	Password          []byte
	ID                int64
}

type UpdateUserRow struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	GroupID           *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsDeleted         bool
	GroupName         string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.SocialNetworkLink,
		arg.PhoneNumber,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.SocialNetworkLink,
		&i.PhoneNumber,
		&i.Email,
		&i.BirthDate,
		&i.Role,
		&i.Password,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.GroupName,
	)
	return i, err
}
