apiVersion: v1
kind: Secret
metadata:
  name: sport-platform-secret
  namespace: sport-platform
type: Opaque
stringData:
  POSTGRES_USER: sport
  POSTGRES_PASSWORD: sport_password
  USERNAME: sport
  PASSWORD: sport_password
  ACCESS_SECRET: dev_access_secret_change_me
  REFRESH_SECRET: dev_refresh_secret_change_me
  AUTH_SECRET: dev_auth_secret_change_me_32_chars
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
