// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clubs.sql

package db_queries

import (
	"context"
	"time"
)

const checkClubExists = `-- name: CheckClubExists :one
SELECT EXISTS(
    SELECT 1 FROM clubs
    WHERE id = $1 AND is_deleted = FALSE
)
`

func (q *Queries) CheckClubExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkClubExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkClubOwnership = `-- name: CheckClubOwnership :one
SELECT EXISTS(
    SELECT 1 FROM clubs
    WHERE id = $1 AND teacher_id = $2 AND is_deleted = false
)
`

type CheckClubOwnershipParams struct {
	ID        int64
	TeacherID int64
}

func (q *Queries) CheckClubOwnership(ctx context.Context, arg CheckClubOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkClubOwnership, arg.ID, arg.TeacherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEducationLevelExistsByName = `-- name: CheckEducationLevelExistsByName :one
SELECT EXISTS(
    SELECT 1 FROM education_levels
    WHERE name = $1
)
`

func (q *Queries) CheckEducationLevelExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEducationLevelExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSportTypeExists = `-- name: CheckSportTypeExists :one
SELECT EXISTS(
    SELECT 1 FROM sport_types
    WHERE id = $1
)
`

func (q *Queries) CheckSportTypeExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkSportTypeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createClub = `-- name: CreateClub :one
INSERT INTO clubs (
    name,
    description,
    sport_type_id,
    teacher_id,
    total_places,
    place,
    education_level_id,
    required_workout_per_week
) VALUES (
             $1,
             $2,
             $3,
             $4,
             $5,
             $6,
             (SELECT id FROM education_levels WHERE education_levels.name = $7),
             $8
         )
    RETURNING id, name, description, sport_type_id, teacher_id, total_places, place, education_level_id, required_workout_per_week, created_at, updated_at, is_deleted
`

type CreateClubParams struct {
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelName     string
	RequiredWorkoutPerWeek int32
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub,
		arg.Name,
		arg.Description,
		arg.SportTypeID,
		arg.TeacherID,
		arg.TotalPlaces,
		arg.Place,
		arg.EducationLevelName,
		arg.RequiredWorkoutPerWeek,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SportTypeID,
		&i.TeacherID,
		&i.TotalPlaces,
		&i.Place,
		&i.EducationLevelID,
		&i.RequiredWorkoutPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllClubs = `-- name: GetAllClubs :many
SELECT
    clubs.id,
    clubs.name,
    clubs.description,
    clubs.sport_type_id,
    clubs.teacher_id,
    clubs.total_places,
    clubs.place,
    clubs.education_level_id,
    clubs.required_workout_per_week,
    clubs.created_at,
    clubs.updated_at,
    clubs.is_deleted,
    sport_types.name as sport_type_name,
    education_levels.name as education_level_name,
    users.full_name as teacher_name
FROM clubs
        JOIN sport_types ON clubs.sport_type_id = sport_types.id AND sport_types.is_deleted = false
        JOIN education_levels ON clubs.education_level_id = education_levels.id AND education_levels.is_deleted = false
        JOIN users ON clubs.teacher_id = users.id AND users.is_deleted = false
WHERE clubs.is_deleted = false
`

type GetAllClubsRow struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
	IsDeleted              bool
	SportTypeName          string
	EducationLevelName     string
	TeacherName            string
}

func (q *Queries) GetAllClubs(ctx context.Context) ([]GetAllClubsRow, error) {
	rows, err := q.db.Query(ctx, getAllClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllClubsRow{}
	for rows.Next() {
		var i GetAllClubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SportTypeID,
			&i.TeacherID,
			&i.TotalPlaces,
			&i.Place,
			&i.EducationLevelID,
			&i.RequiredWorkoutPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.SportTypeName,
			&i.EducationLevelName,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubAttachments = `-- name: GetClubAttachments :many
SELECT attachment_url
FROM club_attachments
WHERE club_id = $1
`

func (q *Queries) GetClubAttachments(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getClubAttachments, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var attachment_url string
		if err := rows.Scan(&attachment_url); err != nil {
			return nil, err
		}
		items = append(items, attachment_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubByID = `-- name: GetClubByID :one
SELECT id, name, description, sport_type_id, teacher_id, total_places, place, education_level_id, required_workout_per_week, created_at, updated_at, is_deleted FROM clubs WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetClubByID(ctx context.Context, id int64) (Club, error) {
	row := q.db.QueryRow(ctx, getClubByID, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SportTypeID,
		&i.TeacherID,
		&i.TotalPlaces,
		&i.Place,
		&i.EducationLevelID,
		&i.RequiredWorkoutPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getClubById = `-- name: GetClubById :one
SELECT
    clubs.id,
    clubs.name,
    clubs.description,
    clubs.sport_type_id,
    clubs.teacher_id,
    clubs.total_places,
    clubs.place,
    clubs.education_level_id,
    clubs.required_workout_per_week,
    clubs.created_at,
    clubs.updated_at,
    clubs.is_deleted,
    sport_types.name as sport_type_name,
    education_levels.name as education_level_name,
    users.full_name as teacher_name
FROM clubs
        JOIN sport_types ON clubs.sport_type_id = sport_types.id AND sport_types.is_deleted = false
        JOIN education_levels ON clubs.education_level_id = education_levels.id AND education_levels.is_deleted = false
        JOIN users ON clubs.teacher_id = users.id AND users.is_deleted = false
WHERE clubs.id = $1 AND clubs.is_deleted = false
`

type GetClubByIdRow struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
	IsDeleted              bool
	SportTypeName          string
	EducationLevelName     string
	TeacherName            string
}

func (q *Queries) GetClubById(ctx context.Context, id int64) (GetClubByIdRow, error) {
	row := q.db.QueryRow(ctx, getClubById, id)
	var i GetClubByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SportTypeID,
		&i.TeacherID,
		&i.TotalPlaces,
		&i.Place,
		&i.EducationLevelID,
		&i.RequiredWorkoutPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.SportTypeName,
		&i.EducationLevelName,
		&i.TeacherName,
	)
	return i, err
}

const getClubsByTeacher = `-- name: GetClubsByTeacher :many
SELECT id, name, description, sport_type_id, teacher_id, total_places, place, education_level_id, required_workout_per_week, created_at, updated_at, is_deleted FROM clubs
WHERE teacher_id = $1 AND is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) GetClubsByTeacher(ctx context.Context, teacherID int64) ([]Club, error) {
	rows, err := q.db.Query(ctx, getClubsByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Club{}
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SportTypeID,
			&i.TeacherID,
			&i.TotalPlaces,
			&i.Place,
			&i.EducationLevelID,
			&i.RequiredWorkoutPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClubs = `-- name: ListActiveClubs :many
SELECT id, name, description, sport_type_id, teacher_id, total_places, place, education_level_id, required_workout_per_week, created_at, updated_at, is_deleted FROM clubs
WHERE is_deleted = false
ORDER BY name
`

func (q *Queries) ListActiveClubs(ctx context.Context) ([]Club, error) {
	rows, err := q.db.Query(ctx, listActiveClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Club{}
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SportTypeID,
			&i.TeacherID,
			&i.TotalPlaces,
			&i.Place,
			&i.EducationLevelID,
			&i.RequiredWorkoutPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClub = `-- name: SoftDeleteClub :exec
UPDATE clubs
SET is_deleted = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteClub(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteClub, id)
	return err
}

const uploadAttachment = `-- name: UploadAttachment :exec
INSERT INTO club_attachments
    (club_id, attachment_url)
VALUES
    ($1, $2)
`

type UploadAttachmentParams struct {
	ClubID        int64
	AttachmentUrl string
}

func (q *Queries) UploadAttachment(ctx context.Context, arg UploadAttachmentParams) error {
	_, err := q.db.Exec(ctx, uploadAttachment, arg.ClubID, arg.AttachmentUrl)
	return err
}
