apiVersion: v1
kind: Secret
metadata:
  name: sport-platform-secret
  labels:
    {{- include "sport-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  USERNAME: {{ .Values.database.user | quote }}
  PASSWORD: {{ .Values.database.password | quote }}
  ACCESS_SECRET: {{ .Values.auth.accessSecret | quote }}
  REFRESH_SECRET: {{ .Values.auth.refreshSecret | quote }}
  AUTH_SECRET: {{ .Values.auth.authSecret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
